image: microsoft/dotnet:latest

stages:
    - build
    - test
    - publish

before_script:
    - apt-get update
    - apt-get install nuget -y
    - nuget restore

build:
    stage: build
    script:
        - dotnet build  --configuration Release

test:
    stage: test
    script:
    - 'dotnet test CSharpExcelChangeHandlerTest/CSharpExcelChangeHandlerTest.csproj --test-adapter-path:. --logger:"junit;LogFilePath=..\artifacts\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"'
    artifacts:
      when: always
      paths:
      - ./**/*test-result.xml
      reports:
        junit:
        - ./**/*test-result.xml


publish:
    stage: publish
    script:
    - chmod +x BuildTools/*.sh
    - ./BuildTools/Build.sh
    artifacts:
      paths:
      - CSharpExcelChangeHandler/bin/Release/*.nupkg
      expire_in: 1 day
    rules:
      - if: $CI_MERGE_REQUEST_ID
        when: never
      - if: $CI_COMMIT_BRANCH == 'master'
        when: on_success
      - if: $CI_COMMIT_TAG
        when: on_success
      - when: never
