image: microsoft/dotnet:latest

stages:
    - build

before_script:
    - apt-get update
    - apt-get install nuget -y
    - nuget restore

build:
    stage: build
    script:
        - dotnet build
