image: microsoft/dotnet:latest

stages:
    - build
    - test

before_script:
    - apt-get update
    - apt-get install nuget -y
    - nuget restore

build:
    stage: build
    script:
        - dotnet build  --configuration Release

test:
    stage: test
    script:
        - dotnet test CSharpExcelChangeLoggerTest/CSharpExcelChangeLoggerTest.csproj
