image: microsoft/dotnet:latest

stages:
    - build
    - test
    - publish

before_script:
    - apt-get update
    - apt-get install nuget -y
    - nuget restore

build:
    stage: build
    script:
        - dotnet build  --configuration Release

test:
    stage: test
    script:
        - dotnet test CSharpExcelChangeLoggerTest/CSharpExcelChangeLoggerTest.csproj

publish:
    stage: publish
    script:
    - chmod +x BuildTools/*.sh
    - ./BuildTools/Build.sh
    artifacts:
      paths:
      - CSharpExcelChangeLogger/bin/Release/*.nupkg
      expire_in: 1 day
    rules:
      - if: '$CI_COMMIT_TAG != ""'
      - if: '$CI_COMMIT_BRANCH == "master"'
      - if: '$CI_COMMIT_BRANCH == "develop"'
      - when: never
