image: microsoft/dotnet:latest

stages:
    - test
    - build

before_script:
    - apt-get update
    - apt-get install nuget build-essential -y
    - nuget restore

test:
    stage: test
    script:
    - 'dotnet test CSharpExcelChangeHandlerTest/CSharpExcelChangeHandlerTest.csproj --test-adapter-path:. --logger:"junit;LogFilePath=..\artifacts\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"'
    artifacts:
      reports:
        junit:
        - ./**/*test-result.xml

package:
    stage: build
    script:
    - make updateVersion
    - make build
    artifacts:
      paths:
      - CSharpExcelChangeHandler/bin/Release/*.nupkg
      expire_in: 1 day

