stages:
    - test
    - build

before_script:
    - apt-get update
    - apt-get install nuget build-essential -y
    - nuget restore

test:
    stage: test
    image: microsoft/dotnet:latest
    script:
    - 'dotnet test ExcelChangeHandlerTest/ExcelChangeHandlerTest.csproj --test-adapter-path:. --logger:"junit;LogFilePath=..\artifacts\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"'
    artifacts:
      reports:
        junit:
        - ./**/*test-result.xml

build_pages:
  stage: test
  image: registry.gitlab.com/pages/hugo/hugo:latest
  script:
    - apk add make
    - make docs/downloadTheme
    - make docs/build
  artifacts:
    paths:
      - docs/public/

pages:
  stage: build
  image: alpine
  only:
    - main
  script:
    - mv docs/public/ public/
  artifacts:
    paths:
      - public/

package:
    stage: build
    image: microsoft/dotnet:latest
    script:
    - make updateVersion
    - make build
    artifacts:
      paths:
      - ExcelChangeHandler/bin/Release/*.nupkg
      expire_in: 1 day

